/**
 * Hand-authored pixel art. Every sprite is rows of palette chars; ' ' is transparent.
 * Rows are padded to equal width at read time, so the art below doesn't need exact alignment.
 * Rendered by components/game/pixel-sprite.tsx via box-shadow pixels (sharp at any scale).
 */

export const PALETTE: Record<string, string> = {
  K: "#180f2e", // outline
  k: "#2a1c4a", // soft outline / shadow
  W: "#ffffff",
  G: "#c8c2e0", // light grey
  g: "#7a7299", // grey
  D: "#3c3363", // dark slate
  R: "#ff6e4d", // accent (tintable)
  r: "#c04024", // accent dark
  Y: "#ffc94a",
  y: "#c58f1e",
  C: "#6ee7ff",
  c: "#2f9fc4",
  E: "#7ee787",
  e: "#3f9e57",
  T: "#a86a3d", // wood
  t: "#6b3f22", // wood dark
  N: "#f0b98a", // skin
  n: "#241522", // hair
  B: "#4a7cff",
  b: "#2b4bb5",
  P: "#b98cff",
  p: "#7a4fc0",
  M: "#ff5fa2",
  S: "#0f0b1f", // screen black
  L: "#e8f5ff", // glass / highlight
};

/** Char that `tint` remaps (the accent colour of a sprite). */
export const TINT_CHAR = "R";

export type SpriteKey = keyof typeof SPRITES;

export const SPRITES = {
  /** Sunny — the player. Faces the camera; CSS flips it for left/right. */
  player: [
    "                ",
    "      nnnnn     ",
    "     nnnnnnn    ",
    "    nnnnnnnnn   ",
    "    nNNNNNNn    ",
    "    NNNNNNNN    ",
    "    KWKNNKWK    ",
    "    NNNNNNNN    ",
    "     NKKKKN     ",
    "      NNNN      ",
    "    RRRRRRRR    ",
    "   NRRRRRRRRN   ",
    "   NRRRRRRRRN   ",
    "    KbbKKbbK    ",
    "    KbbK KbbK   ",
    "    KKK   KKK   ",
  ],
  playerBack: [
    "                ",
    "      nnnnn     ",
    "     nnnnnnn    ",
    "    nnnnnnnnn   ",
    "    nnnnnnnnn   ",
    "    nnnnnnnnn   ",
    "    nnnnnnnnn   ",
    "     nnnnnnn    ",
    "      NNNN      ",
    "     RRRRRR     ",
    "    RRRRRRRR    ",
    "   NRRRRRRRRN   ",
    "   NRRRRRRRRN   ",
    "    KbbKKbbK    ",
    "    KbbK KbbK   ",
    "    KKK   KKK   ",
  ],

  /** Boxy CRT computer on a wooden desk — the 12-year-old's machine. */
  crt: [
    "                ",
    "   KKKKKKKKKK   ",
    "   KGGGGGGGGK   ",
    "   KGSSSSSSGK   ",
    "   KGSEEEESGK   ",
    "   KGSEKKESGK   ",
    "   KGSEEEESGK   ",
    "   KGSSSSSSGK   ",
    "   KGGGGGGGGK   ",
    "   KKKKKKKKKK   ",
    "     KGGGGK     ",
    "  KKKKKKKKKKKK  ",
    "  KTTTTTTTTTTK  ",
    "  KtKttttttKtK  ",
    "  KtK      KtK  ",
    "  KKK      KKK  ",
  ],

  /** Retro console + controller. */
  console: [
    "                ",
    "                ",
    "   KKKKKKKKKK   ",
    "   KDDDDDDDDK   ",
    "   KDGGGGGGDK   ",
    "   KDGRRRRGDK   ",
    "   KDGGGGGGDK   ",
    "   KDDDDDDDDK   ",
    "   KKKKKKKKKK   ",
    "                ",
    "    KKKKKKKK    ",
    "   KDDDDDDDDK   ",
    "   KDWKDDKWDK   ",
    "   KDDDDDDDDK   ",
    "    KKKKKKKK    ",
    "                ",
  ],

  bookshelf: [
    "  KKKKKKKKKKKK  ",
    "  KtttttttttcK  ",
    "  KtRRYYCCEEtK  ",
    "  KtRRYYCCEEtK  ",
    "  KttttttttttK  ",
    "  KtBBMMYYRRtK  ",
    "  KtBBMMYYRRtK  ",
    "  KttttttttttK  ",
    "  KtCCEEBBPPtK  ",
    "  KtCCEEBBPPtK  ",
    "  KttttttttttK  ",
    "  KtYYRRMMCCtK  ",
    "  KtYYRRMMCCtK  ",
    "  KttttttttttK  ",
    "  KKKKKKKKKKKK  ",
    "                ",
  ],

  bed: [
    "                ",
    "  KKKKKKKKKKKK  ",
    "  KTTTTTTTTTTK  ",
    "  KWWWWKRRRRRK  ",
    "  KWWWWKRRRRRK  ",
    "  KWWWWKRRRRRK  ",
    "  KTTTTKRRRRRK  ",
    "  KRRRRRRRRRRK  ",
    "  KRRRRRRRRRRK  ",
    "  KRRRRRRRRRRK  ",
    "  KRRRRRRRRRRK  ",
    "  KTTTTTTTTTTK  ",
    "  KKKKKKKKKKKK  ",
    "  Kt        tK  ",
    "  KK        KK  ",
    "                ",
  ],

  plant: [
    "                ",
    "      E E       ",
    "     EEEEE E    ",
    "    E EEEEEE    ",
    "   EEEEeEEEEE   ",
    "   EEEeEEeEEE   ",
    "    EEEeEEEE    ",
    "     EEeEEE     ",
    "      Ee E      ",
    "      Ee        ",
    "     KKKKKK     ",
    "     KrrrrK     ",
    "     KRRRRK     ",
    "     KRRRRK     ",
    "     KKKKKK     ",
    "                ",
  ],

  /** Workstation: monitor on a desk. Tint per company. */
  desk: [
    "                ",
    "     KKKKKKKK   ",
    "    KDSSSSSSDK  ",
    "    KDSRRRRSDK  ",
    "    KDSRWWRSDK  ",
    "    KDSRRRRSDK  ",
    "    KDSSSSSSDK  ",
    "     KKKKKKKK   ",
    "       KDDK     ",
    "      KKDDKK    ",
    " KKKKKKKKKKKKKK ",
    " KTTTTTTTTTTTTK ",
    " KtKtttttttttKK ",
    " KtK        KtK ",
    " KKK        KKK ",
    "                ",
  ],

  whiteboard: [
    " KKKKKKKKKKKKKK ",
    " KWWWWWWWWWWWWK ",
    " KWRRWWWWWWWWWK ",
    " KWWWRRWWKKKWWK ",
    " KWWWWRRWKWWKWK ",
    " KWKKWWRRKWWKWK ",
    " KWWKKWWWWKKKWK ",
    " KWWWWKKWWWWWWK ",
    " KWCCWWWKKWWWWK ",
    " KWCCWWWWWKKWWK ",
    " KWWWWWWWWWWWWK ",
    " KKKKKKKKKKKKKK ",
    "     KDDDDK     ",
    "    KKDDDDKK    ",
    "    KK    KK    ",
    "                ",
  ],

  servers: [
    "  KKKKKKKKKKKK  ",
    "  KDDDDDDDDDDK  ",
    "  KDgggggggEDK  ",
    "  KDDDDDDDDDDK  ",
    "  KDgggggggEDK  ",
    "  KDDDDDDDDDDK  ",
    "  KDgggggggYDK  ",
    "  KDDDDDDDDDDK  ",
    "  KDgggggggRDK  ",
    "  KDDDDDDDDDDK  ",
    "  KDgggggggEDK  ",
    "  KDDDDDDDDDDK  ",
    "  KDgggggggEDK  ",
    "  KDDDDDDDDDDK  ",
    "  KKKKKKKKKKKK  ",
    "                ",
  ],

  dashboard: [
    " KKKKKKKKKKKKKK ",
    " KSSSSSSSSSSSSK ",
    " KSEESSSSSSSSSK ",
    " KSSEESSSSEESSK ",
    " KSSSEESSEESSSK ",
    " KSSSSEEEESSSSK ",
    " KSSSSSSSSSSSSK ",
    " KSYYSSSSSSYYSK ",
    " KSYYSSYYSSYYSK ",
    " KSYYSSYYSSYYSK ",
    " KSYYYYYYYYYYSK ",
    " KSSSSSSSSSSSSK ",
    " KKKKKKKKKKKKKK ",
    "      KDDK      ",
    "     KKDDKK     ",
    "                ",
  ],

  /** Camera on a tripod — the YouTube corner. */
  camera: [
    "                ",
    "    KKKKKKKKK   ",
    "   KDDDDDDDDDK  ",
    "   KDLLKKKDDDK  ",
    "   KDLKSSKDRDK  ",
    "   KDLKSSKDDDK  ",
    "   KDLLKKKDDDK  ",
    "   KDDDDDDDDDK  ",
    "    KKKKDDKKK   ",
    "       KDDK     ",
    "       KDDK     ",
    "      KDDDDK    ",
    "     KDD  DDK   ",
    "    KDD    DDK  ",
    "   KKK      KKK ",
    "                ",
  ],

  workbench: [
    "                ",
    "                ",
    "      KYYK      ",
    "     KYYYYK     ",
    "   KKKKKKKKKK   ",
    "  KCCKRRKEEKKK  ",
    "  KCCKRRKEEKgK  ",
    " KKKKKKKKKKKKKK ",
    " KTTTTTTTTTTTTK ",
    " KTTTTTTTTTTTTK ",
    " KtKttttttttKtK ",
    " KtK        KtK ",
    " KtK        KtK ",
    " KKK        KKK ",
    "                ",
    "                ",
  ],

  sign: [
    "                ",
    " KKKKKKKKKKKKKK ",
    " KTTTTTTTTTTTTK ",
    " KTKKKTKKKTKKTK ",
    " KTKTTTKTTTKTTK ",
    " KTKKKTKKKTKKTK ",
    " KTTTKTTTTTTTTK ",
    " KTKKKTKKKKKKTK ",
    " KTTTTTTTTTTTTK ",
    " KKKKKKKKKKKKKK ",
    "      KtKK      ",
    "      KtKK      ",
    "      KtKK      ",
    "     KKKKKK     ",
    "                ",
    "                ",
  ],

  globe: [
    "                ",
    "      KKKK      ",
    "    KKBBBBKK    ",
    "   KBBBEEBBBK   ",
    "  KBBEEEBBBBBK  ",
    "  KBEEBBBBEEBK  ",
    " KBBBBBBBEEEBBK ",
    " KBBEEBBBBEEBBK ",
    " KBBEEEBBBBBBBK ",
    "  KBBBBBBEEEBK  ",
    "  KBBBEEBBBBBK  ",
    "   KBBEEEBBBK   ",
    "    KKBBBBKK    ",
    "      KYYK      ",
    "     KKYYKK     ",
    "    KKKKKKKK    ",
  ],

  table: [
    "                ",
    "                ",
    "     KCCKYYK    ",
    " KKKKKKKKKKKKKK ",
    " KTTTTTTTTTTTTK ",
    " KTTTTTTTTTTTTK ",
    " KttttttttttttK ",
    " KKKKKKKKKKKKKK ",
    "   KtK    KtK   ",
    "   KtK    KtK   ",
    "   KtK    KtK   ",
    "   KtK    KtK   ",
    "  KKKKK  KKKKK  ",
    "                ",
    "                ",
    "                ",
  ],

  cafeTable: [
    "                ",
    "      KWWK      ",
    "     KWRRWK     ",
    "     KWWWWK     ",
    "      KKKK      ",
    "  KKKKKKKKKKKK  ",
    "  KTTTTTTTTTTK  ",
    "  KttttttttttK  ",
    "  KKKKKKKKKKKK  ",
    "      KttK      ",
    "      KttK      ",
    "      KttK      ",
    "    KKKKKKKK    ",
    "    KttttttK    ",
    "    KKKKKKKK    ",
    "                ",
  ],

  counter: [
    " KKKKKKKKKKKKKK ",
    " KTTTTTTTTTTTTK ",
    " KTKKKTTTTKKKTK ",
    " KTKRKTYYTKRKTK ",
    " KTKKKTYYTKKKTK ",
    " KTTTTTTTTTTTTK ",
    " KttttttttttttK ",
    " KtKKKKKKKKKKtK ",
    " KtKgggKKgggKtK ",
    " KtKgggKKgggKtK ",
    " KtKKKKKKKKKKtK ",
    " KttttttttttttK ",
    " KtKKKKKKKKKKtK ",
    " KtKKKKKKKKKKtK ",
    " KKKKKKKKKKKKKK ",
    "                ",
  ],

  notice: [
    " KKKKKKKKKKKKKK ",
    " KtttttttttttKK ",
    " KtWWWKtKYYYKtK ",
    " KtWWWKtKYYYKtK ",
    " KtKKKKtKKKKKtK ",
    " KtKCCCKKWWWKtK ",
    " KtKCCCKKWWWKtK ",
    " KtKKKKKKKKKKtK ",
    " KtKRRRKKCCCKtK ",
    " KtKRRRKKCCCKtK ",
    " KtKKKKKKKKKKtK ",
    " KtWWWKKKEEEKtK ",
    " KtWWWKKKEEEKtK ",
    " KttttttttttttK ",
    " KKKKKKKKKKKKKK ",
    "                ",
  ],

  /** Generic community member NPC — tint distinguishes them. */
  npc: [
    "                ",
    "      nnnn      ",
    "     nnnnnn     ",
    "    nnNNNNnn    ",
    "    nNNNNNNn    ",
    "    NNKNNKNN    ",
    "    NNNNNNNN    ",
    "     NNNNNN     ",
    "      NNNN      ",
    "     RRRRRR     ",
    "    RRRRRRRR    ",
    "   NRRRRRRRRN   ",
    "   NRRRRRRRRN   ",
    "    KDDKKDDK    ",
    "    KDDK KDDK   ",
    "    KKK   KKK   ",
  ],

  lectern: [
    "                ",
    "                ",
    "      KWWK      ",
    "    KKKKKKKK    ",
    "   KWWWWWWWWK   ",
    "   KWRRRWWWWK   ",
    "   KWWWWRRRWK   ",
    "   KKKKKKKKKK   ",
    "      KTTK      ",
    "      KTTK      ",
    "      KTTK      ",
    "     KTTTTK     ",
    "    KTTTTTTK    ",
    "   KKKKKKKKKK   ",
    "                ",
    "                ",
  ],

  /** Skill tree panel on the wall — the growth plan. */
  skilltree: [
    " KKKKKKKKKKKKKK ",
    " KSSSSYYSSSSSSK ",
    " KSSSSYYSSSSSSK ",
    " KSSYYYYYYSSSSK ",
    " KSSYSSSSYSSSSK ",
    " KSCYSSSSYERSSK ",
    " KSCCSSSSEERRSK ",
    " KSSSSSSSSSSSSK ",
    " KSYYSSYYSSYYSK ",
    " KSSSSSSSSSSSSK ",
    " KSCCSSEESSRRSK ",
    " KSSSSSSSSSSSSK ",
    " KKKKKKKKKKKKKK ",
    "      KDDK      ",
    "     KKDDKK     ",
    "                ",
  ],

  /** Boss door / portal. */
  door: [
    "  KKKKKKKKKKKK  ",
    "  KRRRRRRRRRRK  ",
    "  KRSSSSSSSSRK  ",
    "  KRSYYSSYYSRK  ",
    "  KRSSSSSSSSRK  ",
    "  KRSSKKKKSSRK  ",
    "  KRSSKKKKSSRK  ",
    "  KRSSSSSSSSRK  ",
    "  KRSSSSSSSSRK  ",
    "  KRSSSSSSSSRK  ",
    "  KRSSSSSSSSRK  ",
    "  KRSSSSSSSSRK  ",
    "  KRSSSSSSSSRK  ",
    "  KRRRRRRRRRRK  ",
    "  KKKKKKKKKKKK  ",
    "                ",
  ],

  trophy: [
    "                ",
    "     KKKKKK     ",
    "    KYYYYYYK    ",
    "   KYYYYYYYYK   ",
    "  KYKYYYYYYKYK  ",
    "  KYKYYYYYYKYK  ",
    "  KYKKYYYYKKYK  ",
    "   KKKYYYYKKK   ",
    "     KYYYYK     ",
    "      KYYK      ",
    "     KKYYKK     ",
    "    KYYYYYYK    ",
    "   KYYYYYYYYK   ",
    "   KKKKKKKKKK   ",
    "                ",
    "                ",
  ],

  cartridge: [
    " KKKKKKKKKKKKKK ",
    " KDDDDDDDDDDDDK ",
    " KDRRRRRRRRRRDK ",
    " KDRSSSSSSSSRDK ",
    " KDRSYYYYYYSRDK ",
    " KDRSSSSSSSSRDK ",
    " KDRRRRRRRRRRDK ",
    " KDDDDDDDDDDDDK ",
    " KDDKKKKKKKKDDK ",
    " KDDKGGGGGGKDDK ",
    " KDDKGKGKGKKDDK ",
    " KDDKGKGKGKKDDK ",
    " KDDKGGGGGGKDDK ",
    " KDDKKKKKKKKDDK ",
    " KKKKKKKKKKKKKK ",
    "                ",
  ],

  coffee: [
    "                ",
    "                ",
    "        C       ",
    "       C C      ",
    "        C       ",
    "  KKKKKKKKKK    ",
    "  KWWWWWWWWKKK  ",
    "  KWttttttWKWK  ",
    "  KWttttttWKWK  ",
    "  KWttttttWKKK  ",
    "  KWWWWWWWWK    ",
    "   KWWWWWWK     ",
    "    KKKKKK      ",
    "   KKKKKKKK     ",
    "   KGGGGGGK     ",
    "   KKKKKKKK      ",
  ],

  laptop: [
    "                ",
    "                ",
    "   KKKKKKKKKK   ",
    "   KDSSSSSSDK   ",
    "   KDSCCCCSDK   ",
    "   KDSCKKCSDK   ",
    "   KDSCCCCSDK   ",
    "   KDSSSSSSDK   ",
    "   KKKKKKKKKK   ",
    "  KKKKKKKKKKKK  ",
    "  KGGGGGGGGGGK  ",
    "  KGKKKKKKKKGK  ",
    "  KGKgggggggGK  ",
    "  KGGGGGGGGGGK  ",
    "  KKKKKKKKKKKK  ",
    "                ",
  ],

  poster: [
    " KKKKKKKKKKKKKK ",
    " KPPPPPPPPPPPPK ",
    " KPYYPPPPPPYYPK ",
    " KPPYYPPPPYYPPK ",
    " KPPPYYYYYYPPPK ",
    " KPPYYRRRRYYPPK ",
    " KPYYRRRRRRYYPK ",
    " KPPYYRRRRYYPPK ",
    " KPPPYYYYYYPPPK ",
    " KPPYYPPPPYYPPK ",
    " KPYYPPPPPPYYPK ",
    " KPPPPPPPPPPPPK ",
    " KPWWWPWWWPWWPK ",
    " KPPPPPPPPPPPPK ",
    " KKKKKKKKKKKKKK ",
    "                ",
  ],
} satisfies Record<string, string[]>;

/** Pads all rows to the widest row so hand-drawn art doesn't need exact alignment. */
export function normalizeSprite(rows: string[]): string[] {
  const width = rows.reduce((max, row) => Math.max(max, row.length), 0);
  return rows.map((row) => row.padEnd(width, " "));
}
